apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.codenow.componentRuntimeName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Values.codenow.componentRuntimeName }}"
data:
  {{- range $key, $val := .Values.environmentVariables }}
  {{ $key -}}: |- {{ $val | b64enc | nindent 4 }}
  {{- end}}
