apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.codenow.componentRuntimeName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Values.codenow.componentRuntimeName }}"
data:
  {{- range $key, $val := .Values.configFiles }}
  {{ $key -}}: |- {{ $val | b64dec | nindent 4 }}
  {{- end}}
