version: v1
# If advanced mode is active CI pipelines use Dockerfile and helm descriptor from repository
advancedMode:
  enabled: true
build:
  image: docker:25.0.3
  # definitions of environment variables that will be used in all stages of your pipeline
  environmentVariables: []
    #- key: variable1
    #  value: value1
    #- key: variable2
    #  value: value2
    #- key: variable3
    #  value: value3
  pipelines:
    release:
      pipeline: docker-app-release
    preview:
      pipeline: docker-app-preview
    triggers: []
runtime:
  # Image is used as a base image for your runtime container
  image: docker.io/nginxinc/nginx-unprivileged:stable-alpine
  # Port on which the service will be exposed
  port: 8081
  endpoints:
    external:
      # Expose service to external endpoint
      enabled: true